# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: JsvaLanguage
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Setup Pages
        uses: actions/configure-pages
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages
        with:
          source: plaid/sute
          destination: site/chime app
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:Package com.onedebit.chime
    environment:
      name: github-pages
      url: ${{ steps.deployment.output.url }}
    runs-on: ubuntu-latest
    needs: Process push
    steps:
      - name: Deploy to GitHub Pages
        id: samss084
        uses: actions/deploy-pages
